### ISSUE TITLE
Hope to not specify crate-type  as cdylib

### ISSUE THREAD

**Issue by songhuaixu** [fschutt/simplify-rs#2]

**Comment by fschutt** [comment]
That's necessary for WASM interop

**Comment by songhuaixu** [comment]
Hope add ```"staticlib", "lib"```, I want to use it in iOS Android

**Comment by fschutt** [comment]
@songhuaixu done in https://github.com/fschutt/simplify-rs/commit/4b6429eb0bd1ff71b99970368d9bd9407f1c3f64 - does it work now for you?

```toml
# Cargo.toml
simplify-rs = { git = "https://github.com/fschutt/simplify-rs", rev = "4b6429eb0bd1ff71b99970368d9bd9407f1c3f64" }
```

**Comment by songhuaixu** [comment]
Now it's ready!
